//! mob_notify_nif — Android local + push notifications tier-1 ZIG plugin NIF.
//!
//! Extracted from mob-core's `mob_nif.zig`: nif_notify_schedule /
//! nif_notify_cancel / nif_notify_register_push (mob_nif.zig:2727-2771
//! pre-strip). The Kotlin side is the plugin-owned bridge class
//! `io.mob.notify.MobNotifyBridge` (NotificationManager + AlarmManager +
//! FirebaseMessaging). Local-notification DELIVERY stays in core/host: the
//! host's NotificationReceiver / MainActivity send through core's
//! mob_deliver_notification. The plugin's own MobFirebaseService and tray-tap
//! handling (MOB-327) send through the thunks below, which reach the same
//! core export, keyed on the shared io.mob.plugin.MobNotifyHub.notifyPid
//! (generated by mob_dev).
//!
//! Delivered message shapes:
//!   {:push_token, :android, token_binary} (exact core parity with
//!   mob_deliver_push_token, mob_nif.zig:2314-2326)
//!   {:notification, map}, sent by mob's :mob_screen router, which decodes
//!   the JSON envelope nativeDeliverNotification hands to core
//!
//! Build path: compiled via `addZigObject` from `-Dplugin_zig_nifs`, reaching
//! mob-core ERTS / JNI bindings through `@import("erts")` / `@import("jni")`.
//! `get_jenv` + `g_jvm` are mob-core exports linked into the same `.so`.
const std = @import("std");
const erts = @import("erts");
const jni = @import("jni");

// mob-core exports (linked into the same .so). NOT duplicated.
extern fn get_jenv(attached: *c_int) ?*jni.JNIEnv;
extern var g_jvm: ?*jni.JavaVM;
// A Mob.Notification JSON envelope to the :mob_screen router, or the queue it
// drains at start (mob >= 0.9.8, android/jni/mob_nif.zig).
extern fn mob_deliver_notification(jpid: jni.JLong, json: [*:0]const u8) void;

// ── Plugin-owned bridge-class method-id cache ────────────────────────────
const NotifyMethods = struct {
    notify_schedule: jni.JMethodID = null,
    notify_cancel: jni.JMethodID = null,
    notify_register_push: jni.JMethodID = null,
    notify_permission_status: jni.JMethodID = null,
};

var g_notify: NotifyMethods = .{};
var g_notify_cls: jni.JClass = null;

// ── nativeRegister thunk — cache the bridge jclass + method ids ───────────
export fn Java_io_mob_notify_MobNotifyBridge_nativeRegister(jenv: *jni.JNIEnv, cls: jni.JClass) callconv(.c) void {
    g_notify_cls = jni.newGlobalRef(jenv, cls);
    if (g_notify_cls == null) return;
    g_notify.notify_schedule = jni.getStaticMethodID(jenv, cls, "notify_schedule", "(JLjava/lang/String;)V");
    g_notify.notify_cancel = jni.getStaticMethodID(jenv, cls, "notify_cancel", "(Ljava/lang/String;)V");
    g_notify.notify_register_push = jni.getStaticMethodID(jenv, cls, "notify_register_push", "(J)V");
    g_notify.notify_permission_status = jni.getStaticMethodID(jenv, cls, "notify_permission_status", "()I");
}

// ── Thread-attach + pid round-trip helpers (mirror mob-core / camera) ─────
inline fn detachIfAttached(attached: c_int) void {
    if (attached != 0) {
        if (g_jvm) |jvm| jni.detachCurrentThread(jvm);
    }
}

inline fn pidToJlong(pid: erts.ErlNifPid) jni.JLong {
    if (@sizeOf(erts.ERL_NIF_TERM) == @sizeOf(jni.JLong)) {
        return @bitCast(pid.pid);
    }
    return @intCast(pid.pid);
}

inline fn pidFromLong(jpid: jni.JLong) erts.ErlNifPid {
    if (@sizeOf(erts.ERL_NIF_TERM) == @sizeOf(jni.JLong)) {
        return .{ .pid = @bitCast(jpid) };
    }
    const low: u32 = @truncate(@as(u64, @bitCast(jpid)));
    return .{ .pid = low };
}

/// {error, bridge_not_registered}: nativeRegister never ran (MobPluginBootstrap
/// did not call register()) or a method-ID lookup failed. Calling into JNI with
/// a null class or method id would abort the VM instead. The public API ignores
/// the return value; MobNotify.SelfTest turns it into a failure (MOB-418).
fn bridgeNotRegistered(env: ?*erts.ErlNifEnv) erts.ERL_NIF_TERM {
    return erts.makeTuple(env, .{ erts.atom(env, "error"), erts.atom(env, "bridge_not_registered") });
}

/// Call `MobNotifyBridge.<method>(pid_long, arg)` — async. Returns :ok, or
/// {error, bridge_not_registered}.
fn callBridgePidStr(env: ?*erts.ErlNifEnv, method: jni.JMethodID, pid: erts.ErlNifPid, arg: ?[*:0]const u8) erts.ERL_NIF_TERM {
    if (g_notify_cls == null or method == null) return bridgeNotRegistered(env);
    var attached: c_int = 0;
    const jenv = get_jenv(&attached) orelse return erts.atom(env, "error");
    const jarg: jni.JString = if (arg) |a| jni.newStringUTF(jenv, a) else null;
    jenv.*.CallStaticVoidMethod.?(jenv, g_notify_cls, method, pidToJlong(pid), jarg);
    if (jarg != null) jni.deleteLocalRef(jenv, jarg);
    detachIfAttached(attached);
    return erts.ok(env);
}

// ── Inbound delivery thunk ────────────────────────────────────────────────

// {:push_token, :android, token_binary} — EXACT replica of core's
// mob_deliver_push_token (mob_nif.zig:2314-2326). register_push's token and
// the refreshes MobFirebaseService.onNewToken receives land here.
export fn Java_io_mob_notify_MobNotifyBridge_nativeDeliverNotifyPushToken(
    jenv: *jni.JNIEnv,
    cls: jni.JClass,
    pid_long: jni.JLong,
    token: jni.JString,
) callconv(.c) void {
    _ = cls;
    var pid = pidFromLong(pid_long);
    const env = erts.enif_alloc_env() orelse return;
    defer erts.enif_free_env(env);

    const token_c = jenv.*.GetStringUTFChars.?(jenv, token, null) orelse return;
    defer jenv.*.ReleaseStringUTFChars.?(jenv, token, token_c);

    const tl = std.mem.len(token_c);
    var tb: erts.ErlNifBinary = undefined;
    if (erts.enif_alloc_binary(tl, &tb) == 0) return;
    @memcpy(tb.data[0..tl], token_c[0..tl]);

    const msg = erts.makeTuple(env, .{
        erts.atom(env, "push_token"),
        erts.atom(env, "android"),
        erts.enif_make_binary(env, &tb),
    });
    _ = erts.enif_send(null, &pid, env, msg);
}

// A Mob.Notification envelope from MobFirebaseService (foreground arrival) or
// MobNotifyFcm (tray tap) → core's mob_deliver_notification, the entry the
// host's MainActivity / NotificationReceiver use for local notifications.
export fn Java_io_mob_notify_MobNotifyBridge_nativeDeliverNotification(
    jenv: *jni.JNIEnv,
    cls: jni.JClass,
    pid_long: jni.JLong,
    json: jni.JString,
) callconv(.c) void {
    _ = cls;
    const json_c = jenv.*.GetStringUTFChars.?(jenv, json, null) orelse return;
    defer jenv.*.ReleaseStringUTFChars.?(jenv, json, json_c);
    mob_deliver_notification(pid_long, json_c);
}

// ── NIFs ──────────────────────────────────────────────────────────────────

// PARITY: core's nif_notify_schedule (mob_nif.zig:2727-2738) passed the JSON
// opts binary straight through to the bridge with the caller pid.
fn nif_notify_schedule(env: ?*erts.ErlNifEnv, argc: c_int, argv: [*]const erts.ERL_NIF_TERM) callconv(.c) erts.ERL_NIF_TERM {
    _ = argc;
    var bin: erts.ErlNifBinary = undefined;
    if (erts.enif_inspect_binary(env, argv[0], &bin) == 0 and
        erts.enif_inspect_iolist_as_binary(env, argv[0], &bin) == 0)
    {
        return erts.badarg(env);
    }
    var buf: [4096]u8 = @splat(0);
    if (bin.size + 1 > buf.len) return erts.badarg(env);
    @memcpy(buf[0..bin.size], bin.data[0..bin.size]);
    var pid: erts.ErlNifPid = undefined;
    _ = erts.enif_self(env, &pid);
    return callBridgePidStr(env, g_notify.notify_schedule, pid, jni.asCStr(&buf));
}

// PARITY: core's nif_notify_cancel (mob_nif.zig:2741-2755) — id string only,
// no pid (cancel has no reply).
fn nif_notify_cancel(env: ?*erts.ErlNifEnv, argc: c_int, argv: [*]const erts.ERL_NIF_TERM) callconv(.c) erts.ERL_NIF_TERM {
    _ = argc;
    var bin: erts.ErlNifBinary = undefined;
    if (erts.enif_inspect_binary(env, argv[0], &bin) == 0 and
        erts.enif_inspect_iolist_as_binary(env, argv[0], &bin) == 0)
    {
        return erts.badarg(env);
    }
    var buf: [256]u8 = @splat(0);
    if (bin.size + 1 > buf.len) return erts.badarg(env);
    @memcpy(buf[0..bin.size], bin.data[0..bin.size]);

    if (g_notify_cls == null or g_notify.notify_cancel == null) return bridgeNotRegistered(env);
    var attached: c_int = 0;
    const jenv = get_jenv(&attached) orelse return erts.atom(env, "error");
    const js: jni.JString = jni.newStringUTF(jenv, jni.asCStr(&buf));
    jenv.*.CallStaticVoidMethod.?(jenv, g_notify_cls, g_notify.notify_cancel, js);
    if (js != null) jni.deleteLocalRef(jenv, js);
    detachIfAttached(attached);
    return erts.ok(env);
}

// PARITY: core's nif_notify_register_push (mob_nif.zig:2761-2770) — pid only
// (core passed a null string arg; the plugin bridge signature drops it).
fn nif_notify_register_push(env: ?*erts.ErlNifEnv, argc: c_int, argv: [*]const erts.ERL_NIF_TERM) callconv(.c) erts.ERL_NIF_TERM {
    _ = argc;
    _ = argv;
    if (g_notify_cls == null or g_notify.notify_register_push == null) return bridgeNotRegistered(env);
    var pid: erts.ErlNifPid = undefined;
    _ = erts.enif_self(env, &pid);
    var attached: c_int = 0;
    const jenv = get_jenv(&attached) orelse return erts.atom(env, "error");
    jenv.*.CallStaticVoidMethod.?(jenv, g_notify_cls, g_notify.notify_register_push, pidToJlong(pid));
    detachIfAttached(attached);
    return erts.ok(env);
}

// Read-only: are this app's notifications enabled? Kotlin answers from
// NotificationManager.areNotificationsEnabled() (posts nothing, prompts
// nothing): 1 = authorized, 0 = denied (switched off, or POST_NOTIFICATIONS not
// granted on 13+), 2 = the bootstrap never handed the bridge an Activity, -1 =
// the query threw. MobNotify.SelfTest's proof that the NIF, the registered
// bridge and the Activity hand-off schedule/cancel need are all in place.
fn nif_notify_permission_status(env: ?*erts.ErlNifEnv, argc: c_int, argv: [*]const erts.ERL_NIF_TERM) callconv(.c) erts.ERL_NIF_TERM {
    _ = argc;
    _ = argv;
    if (g_notify_cls == null or g_notify.notify_permission_status == null) return bridgeNotRegistered(env);
    var attached: c_int = 0;
    const jenv = get_jenv(&attached) orelse return erts.atom(env, "error");
    const code = jenv.*.CallStaticIntMethod.?(jenv, g_notify_cls, g_notify.notify_permission_status);
    detachIfAttached(attached);
    return switch (code) {
        1 => erts.makeTuple(env, .{ erts.atom(env, "ok"), erts.atom(env, "authorized") }),
        0 => erts.makeTuple(env, .{ erts.atom(env, "ok"), erts.atom(env, "denied") }),
        2 => erts.makeTuple(env, .{ erts.atom(env, "error"), erts.atom(env, "no_activity") }),
        else => erts.makeTuple(env, .{ erts.atom(env, "error"), erts.atom(env, "query_failed") }),
    };
}

// ── NIF table + init entry point ─────────────────────────────────────────
fn nifLoad(env: ?*erts.ErlNifEnv, priv: *?*anyopaque, info: erts.ERL_NIF_TERM) callconv(.c) c_int {
    _ = env;
    _ = priv;
    _ = info;
    return 0;
}

const nif_funcs = [_]erts.ErlNifFunc{
    .{ .name = "notify_schedule", .arity = 1, .fptr = nif_notify_schedule, .flags = 0 },
    .{ .name = "notify_cancel", .arity = 1, .fptr = nif_notify_cancel, .flags = 0 },
    .{ .name = "notify_register_push", .arity = 0, .fptr = nif_notify_register_push, .flags = 0 },
    .{ .name = "notify_permission_status", .arity = 0, .fptr = nif_notify_permission_status, .flags = 0 },
};

var nif_entry: erts.ErlNifEntry = .{
    .major = erts.ERL_NIF_MAJOR_VERSION,
    .minor = erts.ERL_NIF_MINOR_VERSION,
    .name = "mob_notify_nif",
    .num_of_funcs = nif_funcs.len,
    .funcs = &nif_funcs,
    .load = nifLoad,
    .reload = null,
    .upgrade = null,
    .unload = null,
    .vm_variant = erts.ERL_NIF_VM_VARIANT,
    .options = 1,
    .sizeof_ErlNifResourceTypeInit = erts.SIZEOF_ErlNifResourceTypeInit,
    .min_erts = erts.ERL_NIF_MIN_ERTS_VERSION,
};

pub export fn mob_notify_nif_nif_init() callconv(.c) *erts.ErlNifEntry {
    return &nif_entry;
}
